---
- name: playbook example
  gather_facts: false
  become: false
  hosts: all
  tasks:
    - name: Install the latest version of Apache and MariaDB
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mariadb-server
