---
- name: playbook example
  gather_facts: false
  become: false
  hosts: all
  tasks:
    - name: install httpd and nginx
      ansible.builtin.yum:
        name:
          - httpd
          - nginx
        state: present
