# Rule W016 - Avoid loop style
---
- name: Playbook example
  gather_facts: false
  become: false
  hosts: all
  - name: Install python and go
    ansible.builtin.yum:
      name:
      - python
      - go

        - nginx
