# Rule W016 - Avoid loop style
---
- name: Playbook example
  gather_facts: false
  become: false
  hosts: all
  tasks:
    - name: Install httpd and nginx
      ansible.builtin.yum:
        name:
        - httpd
        - nginx
        state: present
